// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomSQL: typeof import('./src/components/CustomSQL.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    History: typeof import('./src/components/History.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    NewFile: typeof import('./src/components/NewFile.vue')['default']
    Notes: typeof import('./src/components/Notes.vue')['default']
    Objects: typeof import('./src/components/Objects.vue')['default']
    TableContent: typeof import('./src/components/TableContent.vue')['default']
  }
}
