// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Greet: typeof import('./src/components/Greet.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    NewFile: typeof import('./src/components/NewFile.vue')['default']
    Objects: typeof import('./src/components/Objects.vue')['default']
  }
}
